<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown_Value_Rent_Type_Long_Term</name>
   <tag></tag>
   <elementGuidId>74bf55ea-f478-4ef1-8414-349e2fc59569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mietartDropdown&quot;]/option[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mietartDropdown&quot;]/option[2]</value>
   </webElementProperties>
</WebElementEntity>
