<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Main_Menu_Offer_Dropdown_Create_Offer</name>
   <tag></tag>
   <elementGuidId>3c072943-47a2-4fe0-87ec-5816b52901f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;top_nav_main_menu&quot;]/ul/li[1]/ul/li[9]/a</value>
   </webElementProperties>
</WebElementEntity>
