<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Main_Menu_Offer_Dropdown</name>
   <tag></tag>
   <elementGuidId>b08e1805-2b25-4cf0-aa6f-6ab9e1ef595b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;top_nav_main_menu&quot;]/ul/li[1]</value>
   </webElementProperties>
</WebElementEntity>
